### ISSUE TITLE
[Feature Request] 希望可以保留上次打开的位置和宽度

### ISSUE THREAD

**Issue by seyeeL** [GarinZ/link-map#44] opened 2023-05-10 02:44 UTC
Thank you for submitting an issue for Link Map. To help us better understand your feedback, please fill out the following template(If you think it's too complicated, just write down whatever you want):

## Description
[Describe the issue or feedback you have. Be as specific as possible and provide any relevant details.
## Steps to reproduce (if applicable)
[Include any steps necessary to reproduce the issue, if applicable.]
## Expected behavior
[Describe what you expected to happen.]
## Actual behavior
[Describe what actually happened.]
## Screenshots (if applicable)
[Include screenshots or images to help clarify the issue, if applicable.]
## Additional information
[Include any additional information that may be helpful in resolving the issue.]

Thank you for your feedback.

**Comment by Mansarde** [comment] 2023-05-10 17:05
Duplicate of #31

**Comment by GarinZ** [comment] 2023-05-11 00:27
Hi @seyeeL 
这个功能已经在最新的v1.1.0版本中发布，在插件更新后您就可以看到。

Thanks for @Mansarde  marking  this issue as Duplicate

**Closed as completed by GarinZ** 2023-05-11 00:27 UTC
Labels: help wanted
